atividades/urls.py
from . import views
from django.urls import path
from django.conf.urls import  url

app_name = 'atividades'

urlpatterns = [
    path('', views.index, name="index"),
    url(r'^remove/(?P<id>\d+)/$', views.remove, name='remove'),
]

home/urls.py
from django.urls import path
from django.conf.urls import  url
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
]

projetos/urls.py
from . import views
from django.urls import path
from django.conf.urls import  url

app_name = 'projetos'

urlpatterns = [
    path('', views.index, name="index"),
    path('<str:projeto_id>/atividades/', views.projeto_atividades, name='projeto_atividades'),
    path('<str:projeto_id>/atividades/add/', views.create_atividade, name='add_atividade'),
    path('add/', views.create, name="add"),
    url(r'^remove/(?P<id>\d+)/$', views.remove, name='remove'),
]

visionguard/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', 'home')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('projetos/', include('projetos.urls', 'projetos')),
    path('atividades/', include('atividades.urls', 'atividades')),
]

handler404 = 'views.handler404' 

atividades/models.py
from django.db import models
from django.utils.timezone import now
from projetos.models import Projetos

# Create your models here.
class Atividades(models.Model):
    id = models.AutoField(primary_key=True)
    nm_atividade = models.CharField(max_length=255)
    dt_inicio = models.DateTimeField(editable=False)
    dt_fim = models.DateTimeField(editable=True)
    ind_finalizada = models.BooleanField(default=False, blank=True)
    projeto = models.ForeignKey(Projetos, on_delete=models.CASCADE)

    class Meta:
        db_table = "atividades"

projetos/models.py
from django.db import models

# Create your models here.
class Projetos(models.Model):
    id = models.AutoField(primary_key=True)
    nm_projeto = models.CharField(max_length=255)
    dt_inicio = models.DateTimeField(editable=False)
    dt_fim = models.DateTimeField(editable=True)

    class Meta:
        db_table = "projetos"

atividades/forms/add_atividade_form.py
from django import forms
from django.core.exceptions import ValidationError
from atividades.models import Atividades

class CreateForm(forms.Form):

    nome_atividade = forms.CharField(label='Nome atividade', max_length=255)
    data_inicio = forms.DateField(label='Data Início')
    data_fim = forms.DateField(label='Data Fim')
    ind_finalizada = forms.BooleanField(label='Finalizada?')

    def clean_name(self):
        nome_atividade = self.cleaned_data['nome_atividade']
        r = Atividades.objects.filter(nm_atividade=nome_atividade)
        if r.count():
            raise  ValidationError("Atividade já existe!")
        return nome_atividade

    def save(self, commit=True):
        atividade = Atividades.objects.create(
                    nm_projeto=self.cleaned_data['nome_projeto'],
                    dt_inicio=self.cleaned_data['data_inicio'],
                    dt_fim=self.cleaned_data['data_fim'],
                    ind_finalizada=self.cleaned_data['ind_finalizada'],
                )

        return atividade

projetos/forms/add_atividade_form.py
from django import forms
from django.core.exceptions import ValidationError
from atividades.models import Atividades
from projetos.models import Projetos

class CreateAtividadeForm(forms.Form):

    nome_atividade = forms.CharField(label='Nome atividade', max_length=255)
    data_inicio = forms.DateField(label='Data Início',help_text='Ex: 2021-08-23')
    data_fim = forms.DateField(label='Data Fim',help_text='Ex: 2021-08-23')
    ind_finalizada = forms.BooleanField(label='Finalizada?', required=False)
    #projeto = forms.ModelMultipleChoiceField(queryset=Projetos.objects.all())    

    def __init__(self, projeto, *args, **kwargs):
        self.projeto = projeto       
        super(CreateAtividadeForm, self).__init__(*args, **kwargs) 
    
    def clean_name(self):
        nome_atividade = self.cleaned_data['nome_atividade']
        r = Atividades.objects.filter(nm_atividade=nome_atividade)
        if r.count():
            raise  ValidationError("Atividade já existe!")
        return nome_atividade

    def save(self, commit=True):

        atividade = Atividades.objects.create(
                    nm_atividade=self.cleaned_data['nome_atividade'],
                    dt_inicio=self.cleaned_data['data_inicio'],
                    dt_fim=self.cleaned_data['data_fim'],
                    ind_finalizada=self.cleaned_data['ind_finalizada'],
                    projeto=self.projeto
                )

        return atividade

projetos/forms/add_projeto_form.py
from django import forms
from django.core.exceptions import ValidationError
from projetos.models import Projetos

class CreateForm(forms.Form):

    nome_projeto = forms.CharField(label='Nome projeto', max_length=255)
    data_inicio = forms.DateField(label='Data Início')
    data_fim = forms.DateField(label='Data Fim')

    def clean_name(self):
        nome_projeto = self.cleaned_data['nome_projeto']
        r = Projetos.objects.filter(nm_projeto=nome_projeto)
        if r.count():
            raise  ValidationError("Projeto já existe!")
        return nome_projeto

    def save(self, commit=True):
        projeto = Projetos.objects.create(
                    nm_projeto=self.cleaned_data['nome_projeto'],
                    dt_inicio=self.cleaned_data['data_inicio'],
                    dt_fim=self.cleaned_data['data_fim'],
                )

        return projeto

atividades/views.py
from django.shortcuts import render
from django.conf import settings
from . import urls
from .models import Atividades
from projetos.models import Projetos
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotFound
from django.shortcuts import redirect
from .forms.add_atividade_form import CreateForm


# Create your views here.
@login_required
def index(request):
    projetosList = []

    for projeto in Projetos.objects.all():

        record = {
            'id': projeto.id,
            'nome_projeto': projeto.nm_projeto
        }       

        projetosList.append(record)

    context = {
        'projetosList': projetosList
    }

    return render(request, urls.app_name+'/index.html', context)

@login_required
def remove(request,id):
    atividade = Atividades.objects.get(id=id)
    projeto_id = atividade.projeto.id
    atividade.delete()    
    return redirect('projetos:projeto_atividades',projeto_id)

projetos/views.py
from django.shortcuts import render
from django.conf import settings
from . import urls
from .models import Projetos
from atividades.models import Atividades
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotFound
from django.shortcuts import redirect
from .forms.add_projeto_form import CreateForm
from .forms.add_atividade_form import CreateAtividadeForm


# Create your views here.
@login_required
def index(request):

    projetosList = []

    for projeto in Projetos.objects.all():

        totalAtividades = Atividades.objects.filter(projeto_id=projeto.id).count()
        totalCompletado = Atividades.objects.filter(projeto_id=projeto.id,ind_finalizada=True).count()

        percentualCompleto = 0

        try:
            percentualCompleto = (totalCompletado / totalAtividades) * 100
        except:
            percentualCompleto = 0

        atrasado = "Não"    

        if percentualCompleto < 100:
            atrasado = "Sim"    

        record = {
            'id': projeto.id,
            'nome_projeto': projeto.nm_projeto,
            'data_inicio': projeto.dt_inicio,
            'data_fim': projeto.dt_fim,
            'completo': percentualCompleto,
            'atrasado': atrasado
        }       

        projetosList.append(record)

    context = {
        'projetosList': projetosList
    }

    return render(request, urls.app_name+'/index.html', context)

@login_required
def projeto_atividades(request, projeto_id):

    projeto = Projetos.objects.get(id=projeto_id)
    atividades = Atividades.objects.filter(projeto__id=projeto_id)

    context =  {
        'atividadesList': atividades,
        'projetos': projeto
    }

    return render(request, urls.app_name+'/atividades.html', context)

@login_required
def create(request):
    if request.method == 'POST':

        form = CreateForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('projetos:index')

    else:
        form = CreateForm()

    return render(request, urls.app_name+'/create.html', {'form': form})

@login_required
def create_atividade(request, projeto_id):

    projeto = Projetos.objects.get(id=projeto_id)     

    if request.method == 'POST':

        form = CreateAtividadeForm(projeto, request.POST)

        if form.is_valid():
            form.save()
            return redirect('projetos:projeto_atividades',projeto_id)

    else:
        form = CreateAtividadeForm(projeto)   

    context =  {
        'projetos': projeto,
        'form': form
    }

    return render(request, urls.app_name+'/create_atividade.html', context)

@login_required
def remove(request,id):
    Projetos.objects.filter(id=id).delete()
    return redirect('projetos:index')

projetos/templates/projetos/atividades.html
{% extends "base.html" %}

{% load i18n %}

{% load staticfiles %}

{% block title %} Projetos {% endblock title %}

{% block stylesheets %}

  {{ block.super }}

{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Atividades</h3>
          <h4>Projeto : {{ projetos.nm_projeto }}</h3>
        </div>

      </div>

      <div class="clearfix"></div>

      <div class="row">
	  
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">            

            <div class="x_content">
              <a href={% url 'projetos:add_atividade' projeto_id=projetos.id %}>
              <button class="btn btn-primary">Adicionar</button>
              </a>
              
              <div class="table-responsive">
                <table class="table table-striped jambo_table bulk_action">
                  <thead>
                    <tr class="headings">
                      <th class="column-title">Nome da Atividade </th>
                      <th class="column-title">Data Início </th>
                      <th class="column-title">Data Fim </th>
                      <th class="column-title">Finalizada? </th>
                      <th class="column-title no-link last"><span class="nobr">#</span>
                      </th>
                    </tr>
                  </thead>

                  <tbody>
				    {% for atividade in atividadesList %}
                    <tr class="even pointer">
                      <td class=" ">{{ atividade.nm_atividade }}</td>
                      <td class=" ">{{ atividade.dt_inicio }}</td>
                      <td class=" ">{{ atividade.dt_fim }}</td>
                      <td class=" ">{{ atividade.ind_finalizada|yesno:"Sim,Não" }}</td>
                      <td> <a href={% url 'atividades:remove' id=atividade.id %}>Remover</a> </td>
                    </tr>
					  {% endfor %}		
                  </tbody>
                </table>
              </div>


            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}

  {{ block.super}}  

{% endblock javascripts %}

projetos/templates/projetos/create.html
{% extends "base.html" %}

{% load i18n %}

{% load staticfiles %}

{% block title %} Cadastrar Usuário {% endblock title %}

{% block stylesheets %}

  {{ block.super }}

{% endblock stylesheets %}

{% block content %}

  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Cadastro de Projeto</h3>
        </div>

        <div class="title_right">
          
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">	  

        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Adicionar</h2>
              <div class="clearfix"></div>
            </div>

            <div class="x_content">
                {% if messages %}
                  <ul>
                      {% for message in messages %}
                      <li>{{ message }}</li>
                      {% endfor %}
                  </ul>
              {% endif %}

              <form method="post" class="form-horizontal form-label-left" data-parsley-validate="" novalidate="">
                  {% csrf_token %}

                  {% if form.errors %}
                    <div class="form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                        <div class="alert alert-danger alert-dismissible fade in" role="alert">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
                          </button>
                          Verifique os erros no formulário para continuar
                        </div>
                      </div>  
                    </div>
                  {% endif %}
                  
                  {% for field in form %}
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">{{ field.label }} <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ field }}
                            <ul class="parsley-errors-list filled" id="parsley-id-7">
                            {% for erro in field.errors %}
                              <li class="parsley-required">{{ erro }}</li>
                            {% endfor %}  
                            </ul>
                        </div>
                      </div>    
                  {% endfor %}
                  <div class="ln_solid"></div>  
                  <div class="form-group"> 
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        <button type="submit" class="btn btn-success">Salvar</button>
                    </div>
                  </div>   
              </form>

            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

{% block javascripts %}

  {{ block.super}}  

{% endblock javascripts %}

projetos/templates/projetos/create_atividade.html
{% extends "base.html" %}

{% load i18n %}

{% load staticfiles %}

{% block title %} Cadastrar Atividade {% endblock title %}

{% block stylesheets %}

  {{ block.super }}

{% endblock stylesheets %}

{% block content %}

  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Cadastro de Atividade</h3>
        </div>

        <div class="title_right">
          
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">	  

        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Adicionar ao projeto {{projetos.nm_projeto}}</h2>
              <div class="clearfix"></div>
            </div>

            <div class="x_content">
                {% if messages %}
                  <ul>
                      {% for message in messages %}
                      <li>{{ message }}</li>
                      {% endfor %}
                  </ul>
              {% endif %}

              <form method="post" class="form-horizontal form-label-left" data-parsley-validate="" novalidate="">
                  {% csrf_token %}

                  {% if form.errors %}
                    <div class="form-group">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12"></label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                        <div class="alert alert-danger alert-dismissible fade in" role="alert">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
                          </button>
                          Verifique os erros no formulário para continuar
                        </div>
                      </div>  
                    </div>
                  {% endif %}
                  
                  {% for field in form %}
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">{{ field.label }} <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            {{ field }}
                            <ul class="parsley-errors-list filled" id="parsley-id-7">
                            {% for erro in field.errors %}
                              <li class="parsley-required">{{ erro }}</li>
                            {% endfor %}  
                            </ul>
                        </div>
                      </div>    
                  {% endfor %}
                  <div class="ln_solid"></div>  
                  <div class="form-group"> 
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        <button type="submit" class="btn btn-success">Salvar</button>
                    </div>
                  </div>   
              </form>

            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

{% block javascripts %}

  {{ block.super}}  

{% endblock javascripts %}

projetos/templates/projetos/index.html
{% extends "base.html" %}

{% load i18n %}

{% load staticfiles %}

{% block title %} Projetos {% endblock title %}

{% block stylesheets %}

  {{ block.super }}

{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Projetos</h3>
        </div>

      </div>

      <div class="clearfix"></div>

      <div class="row">
	  
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">            

            <div class="x_content">
              <a href={% url 'projetos:add' %}>
              <button class="btn btn-primary">Adicionar</button>
              </a>
              
              <div class="table-responsive">
                <table class="table table-striped jambo_table bulk_action">
                  <thead>
                    <tr class="headings">
                      <th class="column-title">Nome do Projeto </th>
                      <th class="column-title">Data Início </th>
                      <th class="column-title">Data Fim </th>
                      <th class="column-title">%Completo </th>
                      <th class="column-title">Atrasado </th>
                      <th class="column-title no-link last"><span class="nobr">#</span>
                      </th>
                    </tr>
                  </thead>

                  <tbody>
				    {% for projeto in projetosList %}
                    <tr class="even pointer">
                      <td class=" "><a href={% url 'projetos:index' %}>{{ projeto.nome_projeto }}</a></td>
                      <td class=" ">{{ projeto.data_inicio }}</td>
                      <td class=" ">{{ projeto.data_fim }}</td>
                      <td class=" ">{{ projeto.completo }}</td>
                      <td class=" ">{{ projeto.atrasado }}</td>
                      <td> <a href={% url 'projetos:remove' id=projeto.id %}>Remover</a> </td>
                    </tr>
					  {% endfor %}		
                  </tbody>
                </table>
              </div>


            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}

  {{ block.super}}  

{% endblock javascripts %}