atividades/urls.py
from . import views
from django.urls import path
from django.conf.urls import  url

app_name = 'atividades'

urlpatterns = [
    path('', views.index, name="index"),
    url(r'^remove/(?P<id>\d+)/$', views.remove, name='remove'),
]

home/urls.py
from django.urls import path
from django.conf.urls import  url
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
]

projetos/urls.py
from . import views
from django.urls import path
from django.conf.urls import  url

app_name = 'projetos'

urlpatterns = [
    path('', views.index, name="index"),
    path('<str:projeto_id>/atividades/', views.projeto_atividades, name='projeto_atividades'),
    path('<str:projeto_id>/atividades/add/', views.create_atividade, name='add_atividade'),
    path('add/', views.create, name="add"),
    url(r'^remove/(?P<id>\d+)/$', views.remove, name='remove'),
]

visionguard/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', 'home')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('projetos/', include('projetos.urls', 'projetos')),
    path('atividades/', include('atividades.urls', 'atividades')),
]

handler404 = 'views.handler404' 

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    {% block head %}
      {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Content-Language" content="pt-br">
      {% endblock meta %}

      <title>VisionGuard | {% block title %}{% endblock %}</title>

      {% block stylesheets %}
        <!-- Bootstrap -->
        <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
        <!-- NProgress -->
        <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <link href="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">
        <!-- iCheck -->
        <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">
        <!-- bootstrap-progressbar -->
        <link href="{% static 'vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet">
        <!-- JQVMap -->
        <link href="{% static 'vendors/jqvmap/dist/jqvmap.min.css' %}" rel="stylesheet"/>
      {% endblock stylesheets %}
      <!-- Custom Theme Style -->
      <link href="{% static 'build/css/custom.css' %}" rel="stylesheet">
    {% endblock head %}
  </head>

  <body class="{% block body_class %}nav-md {% endblock body_class %}">
    {% block body %}
      <div class="container body">
        <div class="main_container">

          {% block sidebar %}
            <div class="col-md-3 left_col {% block sidebar_class %} {% endblock sidebar_class %}">
              {% include "sidebar.html" %}
            </div>
          {% endblock sidebar %}

          {% block top_navigation %}
            <div class="top_nav">
              {% include "top_navigation.html" %}
            </div>
          {% endblock top_navigation %}

          {% block content %}
            <!-- {{ content }} -->
          {% endblock content %}

          {% block footer %}
            <footer>
              {% include "footer.html" %}
            </footer>
          {% endblock footer %}
        </div>
      </div>

      {% block javascripts %}
        <!-- jQuery -->
        <script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
        <!-- Bootstrap -->
        <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
        <!-- FastClick -->
        <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
        <!-- NProgress -->
        <script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
        <!-- bootstrap-progressbar -->
        <script src="{% static 'vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
        <!-- iCheck -->
        <script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>
        <script src="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
        <!-- bootstrap-wysiwyg -->
        <script src="{% static 'vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js' %}"></script>
        <script src="{% static 'vendors/jquery.hotkeys/jquery.hotkeys.js' %}"></script>
        <script src="{% static 'vendors/google-code-prettify/src/prettify.js' %}"></script>
        <!-- jQuery Tags Input -->
        <script src="{% static 'vendors/jquery.tagsinput/src/jquery.tagsinput.js' %}"></script>
        <!-- Switchery -->
        <script src="{% static 'vendors/switchery/dist/switchery.min.js' %}"></script>
        <!-- Select2 -->
        <script src="{% static 'vendors/select2/dist/js/select2.full.min.js' %}"></script>
        <!-- Parsley -->
        <script src="{% static 'vendors/parsleyjs/dist/parsley.min.js' %}"></script>
        <script src="{% static 'vendors/parsleyjs/dist/i18n/pt-br.js' %}"></script>
        <!-- Autosize -->
        <script src="{% static 'vendors/autosize/dist/autosize.min.js' %}"></script>
        <!-- jQuery autocomplete -->
        <script src="{% static 'vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js' %}"></script>
        <!-- starrr -->
        <script src="{% static 'vendors/starrr/dist/starrr.js' %}"></script>
      {% endblock %}
      <!-- Custom Theme Scripts -->
      <script src="{% static 'build/js/custom.js' %}"></script>
    {% endblock body %}
  </body>
</html>

templates/footer.html
<div class="pull-right">
  SIMPLTON - Based on Template by <a href="https://colorlib.com/wp/free-bootstrap-admin-dashboard-templates/">Colorlib</a>
</div>
<div class="clearfix"></div>

templates/page_404.html
{% extends "app/base_site.html" %}

{% block title %} Page 404 {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block sidebar %}{% endblock sidebar %}

{% block top_navigation %}{% endblock top_navigation %}

{% block content %}
  <div class="col-md-12">
    <div class="col-middle">
      <div class="text-center text-center">
        <h1 class="error-number">404</h1>
        <h2>Sorry but we couldn't find this page</h2>
        <p>This page you are looking for does not exist <a href="#">Report this?</a>
        </p>
        <div class="mid_center">
          <h3>Search</h3>
          <form>
            <div class="col-xs-12 form-group pull-right top_search">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Go!</button>
                    </span>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block footer %}{% endblock footer %}

{% block javascripts %}
  {{ block.super }}
{% endblock javascripts %}

templates/sidebar.html
{% load staticfiles %}

<div class="left_col scroll-view">

  <div class="navbar nav_title" style="border: 0;">
    <a href="{% url 'admin:index' %}" class="site_title"><i class="fa fa-paw"></i> <span>VisionGuard</span></a>
  </div>

  <div class="clearfix"></div>

  <!-- menu profile quick info -->
  <div class="profile clearfix">
    
    <div class="profile_info">
      <span>Bem vindo,</span>
      <h2>{{ user.email }}</h2>
    </div>
  </div>
  <!-- /menu profile quick info -->

  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <h3>MENU</h3>
      <ul class="nav side-menu">
        <li><a><i class="fa fa-edit"></i> Administração <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href={% url 'projetos:index' %}>Projetos</a></li>
            <li><a href={% url 'atividades:index' %}>Atividades</a></li>
          </ul>
        </li>        
      </ul>
    </div>
    
  </div>
  <!-- /sidebar menu -->

  <!-- /menu footer buttons -->
  <div class="sidebar-footer hidden-small">
    <a data-toggle="tooltip" data-placement="top" title="Settings">
      <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
      <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
      <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
      <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
  </div>
  <!-- /menu footer buttons -->
</div>

templates/top_navigation.html
{% load staticfiles %}

<div class="nav_menu">
  <nav>
    <div class="nav toggle">
      <a id="menu_toggle"><i class="fa fa-bars"></i></a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li class="">
        <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <img src="{% static 'images/img.jpg' %}" alt="">{{ user.email }}
          <span class=" fa fa-angle-down"></span>
        </a>
        <ul class="dropdown-menu dropdown-usermenu pull-right">
          <li><a href="javascript:;"> Minha Conta</a></li>
          <li>
            
          </li>          
          <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out pull-right"></i> Sair do Sistema</a></li>
        </ul>
      </li>

      <li role="presentation" class="dropdown">
        <a href="javascript:;" aria-expanded="false">
           
        </a>        
      </li>
    </ul>
  </nav>
</div>